import 'dotenv/config';
import { db } from '../src/db/index';
import { cmsPages, cmsPageBlocks, users } from '../src/db/schema';
import { eq } from 'drizzle-orm';

const pagesToSeed = [
  { title: 'Help Center', slug: 'help-center', headline: 'How can we help you today?' },
  { title: 'Safety Tips', slug: 'safety-tips', headline: 'Stay Safe on LostFound' },
  { title: 'Community FAQ', slug: 'faq', headline: 'Frequently Asked Questions' },
  { title: 'Success Stories', slug: 'success-stories', headline: 'Heartwarming Recoveries' },
  { title: 'About Us', slug: 'about-us', headline: 'Our Mission to Reconnect' },
  { title: 'Careers', slug: 'careers', headline: 'Join Our Team' },
  { title: 'Press Kit', slug: 'press', headline: 'Press & Media Resources' },
  { title: 'Contact', slug: 'contact', headline: 'Get in Touch' },
  { title: 'Partners', slug: 'partners', headline: 'Partner With Us' },
  { title: 'Premium Features', slug: 'premium', headline: 'Unlock Premium Tools' },
];

async function seed() {
  console.log('Seeding CMS pages...');
  
  const [adminUser] = await db.select().from(users).where(eq(users.role, 'admin')).limit(1);
  const authorId = adminUser ? adminUser.id : null;

  for (const p of pagesToSeed) {
    const existing = await db.select().from(cmsPages).where(eq(cmsPages.slug, p.slug)).limit(1);
    
    if (existing.length === 0) {
      const [newPage] = await db.insert(cmsPages).values({
        title: p.title,
        slug: p.slug,
        status: 'published',
        authorId: authorId,
        seoTitle: `${p.title} | LostFound`,
      }).returning();

      // Add default Hero block
      await db.insert(cmsPageBlocks).values({
        pageId: newPage.id,
        type: 'hero',
        content: {
          headline: p.headline,
          subheading: `Welcome to the ${p.title} page.`,
        },
        orderIndex: 0,
      });

      // Add default Rich Text block
      await db.insert(cmsPageBlocks).values({
        pageId: newPage.id,
        type: 'rich-text',
        content: {
          html: `<h2>Welcome to ${p.title}</h2><p>This page was dynamically generated by the CMS.</p>`
        },
        orderIndex: 1,
      });

      console.log(`Created page: ${p.slug}`);
    } else {
      console.log(`Page already exists: ${p.slug}`);
    }
  }

  console.log('Seeding complete!');
  process.exit(0);
}

seed().catch(console.error);
